services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "${DATABASE_PORT}:5432"


  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8888:8000"
    command: >
      sh -c "poetry run python manage.py migrate --no-input &&
             poetry run python manage.py runserver 0.0.0.0:8000"


volumes:
  postgres_data:
