version: '3.8'

services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "poetry run python manage.py migrate --no-input &&
             poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

volumes:
  postgres_data:
